---
title: "Hello world"
---

**Text editors:** You will need a text editor. Since we're going to be using R, it will be convenient to use [RStudio](https://posit.co/download/rstudio-desktop/) as a text editor. [VS Code](https://code.visualstudio.com/) is another currently popular choice. 


# HTML

Using a text editor, put the code below in a file called `hello1.html`. 

```
<!doctype html>
<meta charset="utf-8">
<title>Hello world</title>
```

Open the file in your web browser. One way to do this is by entering the URL [`file:///`](file:///) in your browser and navigating to the file you created.

* Why `<!doctype html>`? [It makes sure the browser knows we are writing modern HTML5.](https://developer.mozilla.org/en-US/docs/Glossary/Doctype)
* Why `<meta charset="utf-8">`? [It avoids problems with working out the character encoding in some very rare cases.](https://stackoverflow.com/questions/14669352/is-the-charset-attribute-required-with-html5) 
* Why `<title>...</title>`? [It's required.](https://codersblock.com/blog/the-smallest-valid-html5-page/) There is some more standard structure that is implicit and can be omitted: `<html>`, `<head>`, and `<body>`.

# HTML + Javascript

HTML can include code written in Javascript.

Put the code below in a file called `hello2.html`.

```
<!doctype html>
<meta charset="utf-8">
<title>Hello world</title>

<div id="output"></div>

<script>
document.getElementById("output").innerText = "Hello world from Javascript!";
</script>
```

* What is the relationship between Javascript and Java? Nothing. [They are completely different languages.](https://stackoverflow.com/questions/2018731/why-is-javascript-called-javascript-since-it-has-nothing-to-do-with-java)


# Rmarkdown + Javascript

If your data is most easily accessible via R, you might write an [R Markdown](https://rmarkdown.rstudio.com/) document containing both R and Javascript code. Any R code runs when the document is knitted. Any Javascript code runs as the resulting HTML file is loaded in your web browser.

Create a file called `hello2.Rmd` and knit it with `rmarkdown::render("hello2.Rmd")`.

````
--- 
title: Hello world
---

<div id="output"></div>

`r ''````{js}
document.getElementById("output").innerText = "Hello world from Javascript!";
```
````

Open the generated HTML file in a text editor and find your Javascript code in it.


# Delay Javascript until document loaded

I like to be able to read and understand a document from top to bottom, so I like to put outputs below the code and inputs that define them.

Also here I introduce a code pattern of writing an [idempotent][1] `update()` function which is called whenever needed to update the outputs. This will help us write correct (but sometimes inefficient) code.

[1]:  https://stackoverflow.com/questions/1077412/what-is-an-idempotent-operation

````
--- 
title: Hello world
---

`r ''````{js}
function update() {
    document.getElementById("output").innerText = 
        "Hello world from Javascript!";
}

window.addEventListener("load", update);
```

<div id="output"></div>
````

* Why `window.addEventListener`? [It lets you register an event handler without removing any existing event handlers.](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) You could alternatively use `window.onload = update;`, but this wouldn't work if multiple parts of the code wanted to register something to happen on this event.